### PR TITLE
Initial PR for Cinny

### PR DESCRIPTION
**Pull request by Salamandar**
This is the initial PR, the goal of this PR is to run CI jobs to check that everything is fine.

### CODE REVIEW

**Comment by Salamandar** [comment]
!gogogadgetoci

**Comment by ericgaspar** [comment]
How do you start Cinny? there is no systemd.service

**Comment by Salamandar** [comment]
!testme

**Comment by ericgaspar** [comment]
When is Cinny started? systemd.service seems to be missing

**Comment by Salamandar** [comment]
!testme

**Comment by Salamandar** [comment]
Let's merge on master now and ask for app list publication !

**Pull request merged**
